name: Go Linting and Formatting

on:
  push:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Go version from go.mod
      id: go_version
      run: |
        go_version=$(grep '^go ' go.mod | awk '{print $2}')
        if [ -z "$go_version" ]; then
          echo "Error: Go version not found in go.mod"
          exit 1
        fi
        echo "Go version found: $go_version"
        echo "GO_VERSION=$go_version" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}  # Use the Go version extracted from go.mod

    - name: Ensure dependencies are up-to-date
      run: go mod tidy

    - name: Run go fmt
      run: go fmt $(go list ./...)

    - name: Run go vet
      run: go vet -race $(go list ./...)
